Card.create!([
  {name: "衣装デザイン 英梨々", card_id: "W56-046C", note: nil},
  {name: "ライブ衣装 叡智佳", card_id: "W56-095C", note: nil},
  {name: "はじめての完売 出海", card_id: "W56-021C", note: nil},
  {name: "みんなでライブ鑑賞 恵", card_id: "W56-050C", note: nil},
  {name: "みんなで合宿 美智留", card_id: "W56-086U", note: nil},
  {name: "怒りのボルテージ 英梨々", card_id: "W56-042U", note: nil},
  {name: "本気でゲーム作り", card_id: "W56-055CC", note: nil},
  {name: "ドヤ顔で決める 倫也", card_id: "W56-068U", note: nil},
  {name: "徹夜の代償", card_id: "W56-054CC", note: nil},
  {name: "ひやめく天啓 倫也", card_id: "W56-045C", note: nil},
  {name: "懐かしい記憶 美智留", card_id: "W56-094C", note: nil},
  {name: "みんなで合宿 詩羽", card_id: "W56-074C", note: nil},
  {name: "妹系後輩 出海", card_id: "W56-019C", note: nil},
  {name: "むなしい抵抗 英梨々", card_id: "W56-039U", note: nil},
  {name: "対抗意識 英梨々", card_id: "W56-051C", note: nil},
  {name: "衝撃の事実 美智留", card_id: "W56-092C", note: nil},
  {name: "二人の朝 詩羽", card_id: "W56-073C", note: nil},
  {name: "イベントで変装 英梨々", card_id: "W56-020C", note: nil},
  {name: "予想外の言葉 恵", card_id: "W56-049C", note: nil},
  {name: "柏木襟エリのリトラブの色紙", card_id: "W56-026U", note: nil},
  {name: "icy tail 藍子", card_id: "W56-088U", note: nil},
  {name: "縮まる距離 恵", card_id: "W56-075C", note: nil},
  {name: "ジャージでメガネ 英梨々", card_id: "W56-018C", note: nil},
  {name: "ライブ衣装 藍子", card_id: "W56-097C", note: nil},
  {name: "霞詩子の担当編集 苑子", card_id: "W56-069U", note: nil},
  {name: "イメージチャンジ 恵", card_id: "W56-040U", note: nil},
  {name: "八年ぶりの個別ルート", card_id: "W56-027CR", note: nil},
  {name: "演技指導 詩羽", card_id: "W56-047C", note: nil},
  {name: "icy tail 時乃", card_id: "W56-093C", note: nil},
  {name: "強いこだわり 出海", card_id: "W56-016C", note: nil},
  {name: "リトル・ラブ・ラプソティ", card_id: "W56-025U", note: nil},
  {name: "先輩からのアドバイス 詩羽", card_id: "W56-044U", note: nil},
  {name: "icy tailの真実", card_id: "W56-098U", note: nil},
  {name: "恋するメトロノーム", card_id: "W56-079CC", note: nil},
  {name: "icy tail 叡智佳", card_id: "W56-089U", note: nil},
  {name: "みんなで合宿 英梨々", card_id: "W56-014U", note: nil},
  {name: "淡い恋の記憶", card_id: "W56-100CC", note: nil},
  {name: "嬉しき驚き 美智留", card_id: "W56-091C", note: nil},
  {name: "逸脱した中学生 出海", card_id: "W56-023C", note: nil},
  {name: "混乱の極み 詩羽", card_id: "W56-072C", note: nil},
  {name: "ムッとした時の表情 恵", card_id: "W56-048C", note: nil},
  {name: "消えていくハイライト", card_id: "W56-076U", note: nil},
  {name: "企画へのダメ出し 英梨々", card_id: "W56-012U", note: nil},
  {name: "すれ違いデートイベント", card_id: "W56-080CC", note: nil},
  {name: "icy tail", card_id: "W56-099CR", note: nil},
  {name: "凝視する 英梨々", card_id: "W56-022C", note: nil},
  {name: "羞恥心の発露 恵", card_id: "W56-071C", note: nil},
  {name: "憧れの存在 出海", card_id: "W56-017C", note: nil},
  {name: "徹夜でゲーム", card_id: "W56-052U", note: nil},
  {name: "毒舌系先輩 詩羽", card_id: "W56-066U", note: nil},
  {name: "パチモン幼なじみ", card_id: "W56-028CC", note: nil},
  {name: "隠しきれない敵愾心 詩羽", card_id: "W56-070C", note: nil},
  {name: "水辺でのお約束 美智留", card_id: "W56-096C", note: nil},
  {name: "冴えない彼女の育てかた", card_id: "W56-053CR", note: nil},
  {name: "blessing software 美智留", card_id: "W56-090U", note: nil},
  {name: "倫也の企画書", card_id: "W56-024U", note: nil},
  {name: "敵か味方か新キャラか", card_id: "W56-029CC", note: nil},
  {name: "企画へのダメ出し 詩羽", card_id: "W56-067U", note: nil},
  {name: "表情パターン不足 恵", card_id: "W56-043U", note: nil},
  {name: "ライブ衣装 時乃", card_id: "W56-085U", note: nil},
  {name: "頼もしい助っ人", card_id: "W56-030CC", note: nil},
  {name: "ほとばしる才能 出海", card_id: "W56-013U", note: nil},
  {name: "カッコいい男の子 倫也", card_id: "W56-087U", note: nil},
  {name: "オタクの王子様 倫也", card_id: "W56-015U", note: nil},
  {name: "二人の夜の選択肢", card_id: "W56-078CR", note: nil},
  {name: "二人の夜の選択肢", card_id: "W56-078R RRR", note: nil},
  {name: "ねんどろいどぷらす 恵", card_id: "W56-103PR", note: nil},
  {name: "blessing software 詩羽", card_id: "W56-064R", note: nil},
  {name: "譲れない夢 美智留", card_id: "W56-082R", note: nil},
  {name: "ファンシーウェーブ出海", card_id: "W56-010R", note: nil},
  {name: "修羅場突入 英梨々", card_id: "W56-033R", note: nil},
  {name: "意外な贈り物 出海", card_id: "W56-005R", note: nil},
  {name: "過去との対峙 英梨々", card_id: "W56-008R", note: nil},
  {name: "懐かしい記憶 英梨々", card_id: "W56-004R", note: nil},
  {name: "無用の気遣い 恵", card_id: "W56-034R", note: nil},
  {name: "執念の勝利 詩羽", card_id: "W56-060R", note: nil},
  {name: "二人の引き離すもの 英梨々", card_id: "W56-006R", note: nil},
  {name: "クリエイターの闇 詩羽", card_id: "W56-036R", note: nil},
  {name: "六天場モールの戦い 恵", card_id: "W56-063R", note: nil},
  {name: "うろたえる 英梨々", card_id: "W56-011R", note: nil},
  {name: "あまりに薄い存在感 恵", card_id: "W56-038R", note: nil},
  {name: "長い夜のはじまり 詩羽", card_id: "W56-062R", note: nil},
  {name: "多彩な衣装 恵", card_id: "W56-058RR", note: nil},
  {name: "理想の女の子 恵", card_id: "W56-032RR", note: nil},
  {name: "二人の夜 詩羽", card_id: "W56-056RR", note: nil},
  {name: "倫也の愛弟子 出海", card_id: "W56-002RR", note: nil},
  {name: "多彩な衣装 恵", card_id: "W56-058S SR", note: nil},
  {name: "icy tail 美智留", card_id: "W56-081SP SP", note: nil},
  {name: "頼れる先輩 詩羽", card_id: "W56-031S SR", note: nil},
  {name: "頼れる先輩 詩羽", card_id: "W56-031RR", note: nil},
  {name: "クリエータの矜持詩羽", card_id: "W56-059RR", note: nil},
  {name: "ライブ衣装 美智留", card_id: "W56-084R", note: nil},
  {name: "乙女な本質英梨々", card_id: "W56-001RR", note: nil},
  {name: "ねんどろいどぷらす　詩羽", card_id: "W56-104PR", note: nil},
  {name: "謎の威圧感 恵", card_id: "W56-041U", note: nil},
  {name: "blessing software 詩羽", card_id: "W56-064S SR", note: nil},
  {name: "夢を叶えるまでの物語 恵", card_id: "W56-057RR", note: nil},
  {name: "倫也の企画書", card_id: "W56-077U", note: nil},
  {name: "ねんどろいどぷらす 美智留", card_id: "W56-105PR", note: nil},
  {name: "あまりにも薄い存在感 恵", card_id: "W56-038S SR", note: "遊楽舎 新品"},
  {name: "ツンデレ系幼なじみ 英梨々", card_id: "W56-003RR", note: "遊楽舎 新品"},
  {name: "フラグの立たない彼女 恵", card_id: "W56-035R", note: "遊楽舎 新品"},
  {name: "原始の幼なじみ 美智留", card_id: "W56-083R", note: "遊楽舎 新品"},
  {name: "blessing softwatre 英梨々", card_id: "W56-007R", note: "遊楽舎 新品"},
  {name: "下品な煽り 詩羽", card_id: "W56-061R", note: "遊楽舎 新品"},
  {name: "blessing software 恵", card_id: "W56-037R", note: "遊楽舎 新品"},
  {name: "戦いの朝 出海", card_id: "W56-009R", note: "遊楽舎 新品"},
  {name: "icy tail 美智留", card_id: "W56-081RR", note: "遊楽舎 新品"},
  {name: "フラグの立たない彼女 恵", card_id: "W56-035S SR", note: "遊楽舎 新品"},
  {name: "八年ぶりの個別ルート", card_id: "W56-027R RRR", note: "遊楽舎 新品"},
  {name: "ライブ衣装 美智留", card_id: "W56-084S SR", note: "遊楽舎 新品"},
  {name: "二人を引き離すもの 英梨々", card_id: "W56-006S SR", note: "遊楽舎 新品"},
  {name: "原始の幼なじみ 美智留", card_id: "W56-083S SR", note: "カードラボ 天神"},
  {name: "倫也の愛弟子 出海", card_id: "W56-002SP SP", note: "Yellow Submarine 天神"},
  {name: "メインヒロイン担当 恵", card_id: "W56-T04R RRR", note: "Yellow Submarine 天神"},
  {name: "ツンデレ幼なじみ 英梨々", card_id: "W56-003S SR", note: "Yellow Submarine 天神"},
  {name: "すれ違いデートイベント", card_id: "W56-080R RRR", note: "Yellow Submarine 天神"},
  {name: "敵か味方か新キャラか", card_id: "W56-029R RRR", note: "Yellow Submarine 天神"},
  {name: "ねんどろいどぷらす 出海", card_id: "W56-102PR", note: "Yellow Submarine 天神"},
  {name: "冴えない彼女の育てかた", card_id: "W56-053R RRR", note: "Yellow Submarine 天神"},
  {name: "夢を叶えるまでの物語 恵", card_id: "W56-057S SR", note: "Yellow Submarine 天神"},
  {name: "意外な贈り物 出海", card_id: "W56-005S SR", note: "Yellow Submarine 天神"},
  {name: "ねんどろいどぷらす 英梨々", card_id: "W56-101PR", note: "駿河屋"}
])
